---
functional:
  - Пользователь должен иметь возможность создавать игры
  - Пользователь должен иметь возможность просматривать интерфейс сервиса и просматривать подробную информацию о пользователях
  - Пользователь должен иметь возможность просматривать игры в записи
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Сайт должен соблюдать действубщее законодательсвто
  - На сайте должно быть размещено полное юридическое название организации и адрес
  - Сайт должен быть понятным пользователю
